name: cd

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    timeout-minutes: 30

    env:
      GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY}}

    steps:
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23.2"

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build the Application
        run: scripts/buildprod.sh

      - id: "auth"
        uses: "google-github-actions/auth@v2"
        with:
          credentials_json: "${{ secrets.GCP_CREDENTIALS }}"

      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v2"

      - name: "Use gcloud CLI"
        run: "gcloud info"

      - name: Build Docker Image and Push to Google Artifact Registry
        run: "gcloud builds submit --tag asia-southeast1-docker.pkg.dev/twoshops/twoshops-ar-repo/twoshops-be:latest ."

      - name: Deploy to Cloud Run
        run: gcloud run deploy twoshops --image asia-southeast1-docker.pkg.dev/twoshops/twoshops-ar-repo/twoshops-be:latest --region asia-southeast1 --allow-unauthenticated --project twoshops --max-instances=1
